### ISSUE TITLE
Need Onliner using ffuf for XSS automation

### ISSUE THREAD

**Issue by sywahh** [0xPugal/One-Liners#1]
try to code with list of XSS urls extracted from waybackurls or gau.
pass that target urls file to ffuf with custom payload list.

**Comment by dody200411** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>4gcON4

**Comment by dody200411** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>tzxvXa

**Comment by dody200411** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>RgRGqA

**Comment by dody200411** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>SbW4xl

**Comment by dody200411** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>rxyf5Q

**Comment by dody200411** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>bJVgDL

**Comment by dody200411** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>Hjnkfr

**Comment by dody200411** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>zqdeW8

**Comment by dody200411** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>VIXvsJ

**Comment by dody200411** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>g1G1yy

**Comment by dody200411** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>Wly6tb

**Comment by dody200411** [comment]
'"></script><div rNnTRbt=roann>zfKsaI

**Comment by dody200411** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>rDEdBL

**Comment by dody200411** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>qM6fpy

**Comment by dody200411** [comment]
'" rNnTRbt="roannATTR" x=yTgoE6t

**Comment by dody200411** [comment]
'"><div rNnTRbt=roann>o9UDnb

**Comment by dody200411** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>72SlNH

**Comment by dody200411** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>vRApRE

**Comment by dody200411** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>4mA6Cs

**Comment by dody200411** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>sZJtMs

**Comment by dody200411** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>Xyd1dU

**Comment by dody200411** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>diglvN

**Comment by dody200411** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>lPo1wd

**Comment by dody200411** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>HpZcit

**Comment by dody200411** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>XJyeAV

**Comment by dody200411** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>iVDCnu

**Comment by dody200411** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>I97Uw0

**Comment by dody200411** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>kv3sFU

**Comment by dody200411** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>7a08fU

**Comment by dody200411** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>5LfeMG

**Comment by dody200411** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>fsNCQ0

**Comment by dody200411** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>TpWck1

**Comment by dody200411** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>yE78D4

**Comment by dody200411** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>AmS4Ex

**Comment by dody200411** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>1yGzPT

**Comment by dody200411** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>gOSUvb

**Comment by dody200411** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>oh15Uq

**Comment by dody200411** [comment]
rNnTRbt=1 x=d'"><div rNnTRbt='1'>DGdtA3
