### ISSUE TITLE
Censys Subdomains CLI

### ISSUE THREAD

**Issue by thehappydinoa** [0xPugal/One-Liners#6]
Hey there, love this list, I thought you might be interested that censys has a subdomains command in the CLI: <https://censys-python.readthedocs.io/en/stable/usage-cli.html#subdomains>

**Comment by 0xPugal** [comment]
Done! https://github.com/0xPugazh/One-Liners/commit/1a13cabf0295f0557632e6d046fbcdf4da78d702
